# Check https://circleci.com/docs/2.0/language-javascript/ for more details

cache_key: &cache_key
  dependencies-v1-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "esy.lock.json" }}

steps: &steps
- checkout

- run:
    name: Setup environment variables
    command: |
      echo 'export NPM_CONFIG_PREFIX="$HOME/.npm-global"' >> $BASH_ENV
      echo 'export PATH="$NPM_CONFIG_PREFIX/bin:$PATH"' >> $BASH_ENV
      echo "export RELEASE_OS=$(uname | tr '[A-Z]' '[a-z]')" >> $BASH_ENV

- run:
    name: Ensure rsync is installed
    command: |
      if [ "$RELEASE_OS" = "linux" ]; then
        sudo apt-get install -qy rsync;
      fi

# Download and cache dependencies
- restore_cache:
    keys:
    - *cache_key

- run: npm install -g esy@0.5.8
- run: esy install
- run: esy build

- save_cache:
    paths:
      - ~/.esy
      # - ~/.esy/3/i
      # - ~/.esy/source-tarballs
    key: *cache_key

- run:
    name: Format
    command: esy format

- run:
    name: Check dirty workspace
    command: git diff --no-ext-diff --quiet --exit-code

- run:
    name: Run esy test
    command: esy test

environment: &environment
- TERM: dumb

working_directory: &working_directory
  ~/repo

version: 2
jobs:
  macos:
    macos:
      xcode: "9.2.0"

    working_directory: *working_directory
    environment: *environment
    steps: *steps

  linux:
    docker:
    - image: circleci/node:12.13.1-stretch-browsers

    working_directory: *working_directory
    environment: *environment
    steps: *steps

workflows:
  version: 2
  build-deploy:
    jobs:
    - linux
    # - macos
